INSERT INTO products (name, brand, technical_details, color, price, image_url)
VALUES
('LITE 92', 'Ultralight', 'Rimless titanium design; deep rectangular frames; simple dipped bridge; razor-thin sides tapering into elongated temple tips; lightweight for all-day comfort.', 'Green', 345.25, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/lite92.png'),
('FERN', 'LUXe', 'Pilot-style acetate frames; glossy finish; temple detail with two-tone temple tips; tapered sides with double pin detail; double bridge; made from 91% recycled materials.', 'Green', 499.31, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/fern.png'),
('MIMCO 01', 'MIMCO', 'Bold acetate frames; signature MIMCO detailing on temples; comfortable fit; suitable for all-day wear.', 'Black', 229.99, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/mimco.png'),
('ALEX PERRY 23', 'Alex Perry', 'Elegant metal frames; intricate detailing on the temples; lightweight design; perfect for a sophisticated look.', 'Gold', 279.00, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/alex-perry.png'),
('COUNTRY ROAD 07', 'Country Road', 'Classic rectangular frames; subtle branding on temples; durable acetate construction; ideal for everyday wear.', 'Tortoiseshell', 299.75, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/country-road.png'),
('TED BAKER 155', 'Ted Baker', 'Stylish round frames; unique patterned temples; comfortable nose pads; adds a touch of flair to any outfit.', 'Gold', 299.01, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/ted-baker.png'),
('HUGO 05', 'HUGO', 'Sleek metal frames; minimalist design; flexible hinges for added comfort; embodies modern elegance.', 'Silver', 299.78, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/hugo.png'),
('FLORENCE BY MILLS 02', 'Florence by Mills', 'Playful cat-eye frames; lightweight acetate material; designed for a youthful look; comfortable for extended wear.', 'Pink', 199.98, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/florence-by-mills.png'),
('ADIDAS ORIGIN 21', 'Adidas Originals', 'Sporty rectangular frames; durable materials; subtle Adidas branding; perfect for an active lifestyle.', 'Black', 199.01, 'https://github.com/renatomatos79/cgi-python-adventure/blob/main/images/glasses/adidas-originals.png');
